project: 
  type: website
  output-dir: _site
  
website: 
  title: "Camille Magneville"
  
  navbar: 
    left:
    - href: index.qmd
      text: Camille Magneville
    - href: about.qmd
      text: About
    - href: research.qmd
      text: Research
    
    right:
    - icon: github
      href: https://github.com/CmlMagneville/CmlMagneville.github.io
      
  page-footer:
    center: "Built with [Quarto](https://quarto.org/)"
  
format:
  html:
    theme: flatly
    toc: false
    
  