project: 
  type: website
  output-dir: _site
  
website: 
  title: "Camille Magneville"
  site-url: https://cmlmagneville.github.io/
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
        
    right:
      - text: "{{< iconify fa6-brands:google-scholar >}}"
        href: https://scholar.google.com/citations?user=PnnVbAgAAAAJ&hl=fr&authuser=2
      - text: "{{< iconify meteor-icons:bluesky >}}"
        href: https://bsky.app/profile/cmlmagneville.bsky.social
      - icon: github
        href: https://github.com/CmlMagneville 
      - icon: LinkedIn
        href: https://www.linkedin.com/in/camille-magneville-841ba7163/ 

  page-footer: 
    right: "Built with [Quarto](https://quarto.org/)"
    left: |
      <div>&copy; Copyright 2026, Camille Magneville</div>

      <div id="cookie-banner-placeholder"></div>
      
      <script>
        function loadGoogleAnalytics() {
          const gascript = document.createElement("script");
          gascript.async = true;
          gascript.src = "https://www.googletagmanager.com/gtag/js?id=G-DV6K7C0XDV";
          document.head.appendChild(gascript);
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-DV6K7C0XDV');
        }

        document.addEventListener("DOMContentLoaded", function () {
          if (localStorage.getItem("cookieAccepted") === "true") {
            loadGoogleAnalytics();
            return;
          }
          const bannerHTML = `
            <div id="cookie-banner">
              <p>
                This website uses cookies for analytics. By clicking "OK", you agree to its use.
                <button id="accept-cookies">OK</button>
                <a href="privacy.html" class="cookie-link">(learn more)</a>
              </p>
            </div>`;
          document.getElementById("cookie-banner-placeholder").innerHTML = bannerHTML;
          
          document.getElementById("accept-cookies").addEventListener("click", function () {
            localStorage.setItem("cookieAccepted", "true");
            document.getElementById("cookie-banner").remove();
            loadGoogleAnalytics();
          });
        });
      </script>
    

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    navigation:
      sidebar: false
    meta:
      description: "Personal website of Camille Magneville"
      author: "Camille Magneville"
      keywords: ["Camille Magneville", "functional ecology", "coastal marine ecsosystems", "conservation", "temporal variability", "teaching"]

editor: source
